//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCLib.FlotationDevice.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationCollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocationCollection()
        {
            this.Shelvings = new HashSet<Shelving>();
        }
    
        public int LocationCollectionID { get; set; }
        public int LocationID { get; set; }
        public int CollectionID { get; set; }
        public Nullable<int> CheckedInItems { get; set; }
    
        public virtual Collection Collection { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shelving> Shelvings { get; set; }
    }
}
