//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCLib.FlotationDevice.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShelfType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShelfType()
        {
            this.Shelvings = new HashSet<Shelving>();
        }
    
        public int ShelfTypeID { get; set; }
        public string ShelfType1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shelving> Shelvings { get; set; }
    }
}
