//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCLib.FlotationDevice.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shelving
    {
        public int ShelvingID { get; set; }
        public int LocationCollectionID { get; set; }
        public int ShelfTypeID { get; set; }
        public Nullable<int> ShelfQty { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> RowQty { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public int CollectionID { get; set; }
        public int LocationID { get; set; }
    
        public virtual LocationCollection LocationCollection { get; set; }
        public virtual ShelfType ShelfType { get; set; }
        public virtual Collection Collection { get; set; }
        public virtual Location Location { get; set; }
    }
}
