//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 9/9/2019 3:05:03 PM
namespace HCLib.FlotationDevice.Service.Models
{
    /// <summary>
    /// There are no comments for LocationCollectionSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("LocationCollectionSingle")]
    public partial class LocationCollectionSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<LocationCollection>
    {
        /// <summary>
        /// Initialize a new LocationCollectionSingle object.
        /// </summary>
        public LocationCollectionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new LocationCollectionSingle object.
        /// </summary>
        public LocationCollectionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new LocationCollectionSingle object.
        /// </summary>
        public LocationCollectionSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<LocationCollection> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Collection in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Collection")]
        public global::HCLib.FlotationDevice.Service.Models.CollectionSingle Collection
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Collection == null))
                {
                    this._Collection = new global::HCLib.FlotationDevice.Service.Models.CollectionSingle(this.Context, GetPath("Collection"));
                }
                return this._Collection;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::HCLib.FlotationDevice.Service.Models.CollectionSingle _Collection;
        /// <summary>
        /// There are no comments for Location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Location")]
        public global::HCLib.FlotationDevice.Service.Models.LocationSingle Location
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Location == null))
                {
                    this._Location = new global::HCLib.FlotationDevice.Service.Models.LocationSingle(this.Context, GetPath("Location"));
                }
                return this._Location;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::HCLib.FlotationDevice.Service.Models.LocationSingle _Location;
        /// <summary>
        /// There are no comments for Shelvings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Shelvings")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Shelving> Shelvings
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Shelvings == null))
                {
                    this._Shelvings = Context.CreateQuery<global::HCLib.FlotationDevice.Service.Models.Shelving>(GetPath("Shelvings"));
                }
                return this._Shelvings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Shelving> _Shelvings;
    }
    /// <summary>
    /// There are no comments for LocationCollection in the schema.
    /// </summary>
    /// <KeyProperties>
    /// LocationCollectionID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("LocationCollectionID")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("LocationCollection")]
    public partial class LocationCollection : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new LocationCollection object.
        /// </summary>
        /// <param name="locationCollectionID">Initial value of LocationCollectionID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static LocationCollection CreateLocationCollection(int locationCollectionID)
        {
            LocationCollection locationCollection = new LocationCollection();
            locationCollection.LocationCollectionID = locationCollectionID;
            return locationCollection;
        }
        /// <summary>
        /// There are no comments for Property LocationCollectionID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LocationCollectionID")]
        public int LocationCollectionID
        {
            get
            {
                return this._LocationCollectionID;
            }
            set
            {
                this.OnLocationCollectionIDChanging(value);
                this._LocationCollectionID = value;
                this.OnLocationCollectionIDChanged();
                this.OnPropertyChanged("LocationCollectionID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private int _LocationCollectionID;
        partial void OnLocationCollectionIDChanging(int value);
        partial void OnLocationCollectionIDChanged();
        /// <summary>
        /// There are no comments for Property LocationID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LocationID")]
        public global::System.Nullable<int> LocationID
        {
            get
            {
                return this._LocationID;
            }
            set
            {
                this.OnLocationIDChanging(value);
                this._LocationID = value;
                this.OnLocationIDChanged();
                this.OnPropertyChanged("LocationID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<int> _LocationID;
        partial void OnLocationIDChanging(global::System.Nullable<int> value);
        partial void OnLocationIDChanged();
        /// <summary>
        /// There are no comments for Property CollectionID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CollectionID")]
        public global::System.Nullable<int> CollectionID
        {
            get
            {
                return this._CollectionID;
            }
            set
            {
                this.OnCollectionIDChanging(value);
                this._CollectionID = value;
                this.OnCollectionIDChanged();
                this.OnPropertyChanged("CollectionID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<int> _CollectionID;
        partial void OnCollectionIDChanging(global::System.Nullable<int> value);
        partial void OnCollectionIDChanged();
        /// <summary>
        /// There are no comments for Property CheckedInItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CheckedInItems")]
        public global::System.Nullable<int> CheckedInItems
        {
            get
            {
                return this._CheckedInItems;
            }
            set
            {
                this.OnCheckedInItemsChanging(value);
                this._CheckedInItems = value;
                this.OnCheckedInItemsChanged();
                this.OnPropertyChanged("CheckedInItems");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<int> _CheckedInItems;
        partial void OnCheckedInItemsChanging(global::System.Nullable<int> value);
        partial void OnCheckedInItemsChanged();
        /// <summary>
        /// There are no comments for Property Collection in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Collection")]
        public global::HCLib.FlotationDevice.Service.Models.Collection Collection
        {
            get
            {
                return this._Collection;
            }
            set
            {
                this.OnCollectionChanging(value);
                this._Collection = value;
                this.OnCollectionChanged();
                this.OnPropertyChanged("Collection");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::HCLib.FlotationDevice.Service.Models.Collection _Collection;
        partial void OnCollectionChanging(global::HCLib.FlotationDevice.Service.Models.Collection value);
        partial void OnCollectionChanged();
        /// <summary>
        /// There are no comments for Property Location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Location")]
        public global::HCLib.FlotationDevice.Service.Models.Location Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                this._Location = value;
                this.OnLocationChanged();
                this.OnPropertyChanged("Location");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::HCLib.FlotationDevice.Service.Models.Location _Location;
        partial void OnLocationChanging(global::HCLib.FlotationDevice.Service.Models.Location value);
        partial void OnLocationChanged();
        /// <summary>
        /// There are no comments for Property Shelvings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Shelvings")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.Shelving> Shelvings
        {
            get
            {
                return this._Shelvings;
            }
            set
            {
                this.OnShelvingsChanging(value);
                this._Shelvings = value;
                this.OnShelvingsChanged();
                this.OnPropertyChanged("Shelvings");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.Shelving> _Shelvings = new global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.Shelving>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnShelvingsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.Shelving> value);
        partial void OnShelvingsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CollectionSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CollectionSingle")]
    public partial class CollectionSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Collection>
    {
        /// <summary>
        /// Initialize a new CollectionSingle object.
        /// </summary>
        public CollectionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CollectionSingle object.
        /// </summary>
        public CollectionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CollectionSingle object.
        /// </summary>
        public CollectionSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Collection> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for LocationCollections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LocationCollections")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.LocationCollection> LocationCollections
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._LocationCollections == null))
                {
                    this._LocationCollections = Context.CreateQuery<global::HCLib.FlotationDevice.Service.Models.LocationCollection>(GetPath("LocationCollections"));
                }
                return this._LocationCollections;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.LocationCollection> _LocationCollections;
        /// <summary>
        /// There are no comments for Shelvings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Shelvings")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Shelving> Shelvings
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Shelvings == null))
                {
                    this._Shelvings = Context.CreateQuery<global::HCLib.FlotationDevice.Service.Models.Shelving>(GetPath("Shelvings"));
                }
                return this._Shelvings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Shelving> _Shelvings;
    }
    /// <summary>
    /// There are no comments for Collection in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CollectionID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("CollectionID")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Collection")]
    public partial class Collection : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Collection object.
        /// </summary>
        /// <param name="collectionID">Initial value of CollectionID.</param>
        /// <param name="active">Initial value of Active.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static Collection CreateCollection(int collectionID, bool active)
        {
            Collection collection = new Collection();
            collection.CollectionID = collectionID;
            collection.Active = active;
            return collection;
        }
        /// <summary>
        /// There are no comments for Property CollectionID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CollectionID")]
        public int CollectionID
        {
            get
            {
                return this._CollectionID;
            }
            set
            {
                this.OnCollectionIDChanging(value);
                this._CollectionID = value;
                this.OnCollectionIDChanged();
                this.OnPropertyChanged("CollectionID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private int _CollectionID;
        partial void OnCollectionIDChanging(int value);
        partial void OnCollectionIDChanged();
        /// <summary>
        /// There are no comments for Property CollectionName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CollectionName")]
        public string CollectionName
        {
            get
            {
                return this._CollectionName;
            }
            set
            {
                this.OnCollectionNameChanging(value);
                this._CollectionName = value;
                this.OnCollectionNameChanged();
                this.OnPropertyChanged("CollectionName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _CollectionName;
        partial void OnCollectionNameChanging(string value);
        partial void OnCollectionNameChanged();
        /// <summary>
        /// There are no comments for Property CollectionCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CollectionCode")]
        public string CollectionCode
        {
            get
            {
                return this._CollectionCode;
            }
            set
            {
                this.OnCollectionCodeChanging(value);
                this._CollectionCode = value;
                this.OnCollectionCodeChanged();
                this.OnPropertyChanged("CollectionCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _CollectionCode;
        partial void OnCollectionCodeChanging(string value);
        partial void OnCollectionCodeChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Active")]
        public bool Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this._Active = value;
                this.OnActiveChanged();
                this.OnPropertyChanged("Active");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private bool _Active;
        partial void OnActiveChanging(bool value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for Property AverageWidth in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AverageWidth")]
        public global::System.Nullable<double> AverageWidth
        {
            get
            {
                return this._AverageWidth;
            }
            set
            {
                this.OnAverageWidthChanging(value);
                this._AverageWidth = value;
                this.OnAverageWidthChanged();
                this.OnPropertyChanged("AverageWidth");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<double> _AverageWidth;
        partial void OnAverageWidthChanging(global::System.Nullable<double> value);
        partial void OnAverageWidthChanged();
        /// <summary>
        /// There are no comments for Property LocationCollections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LocationCollections")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.LocationCollection> LocationCollections
        {
            get
            {
                return this._LocationCollections;
            }
            set
            {
                this.OnLocationCollectionsChanging(value);
                this._LocationCollections = value;
                this.OnLocationCollectionsChanged();
                this.OnPropertyChanged("LocationCollections");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.LocationCollection> _LocationCollections = new global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.LocationCollection>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnLocationCollectionsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.LocationCollection> value);
        partial void OnLocationCollectionsChanged();
        /// <summary>
        /// There are no comments for Property Shelvings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Shelvings")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.Shelving> Shelvings
        {
            get
            {
                return this._Shelvings;
            }
            set
            {
                this.OnShelvingsChanging(value);
                this._Shelvings = value;
                this.OnShelvingsChanged();
                this.OnPropertyChanged("Shelvings");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.Shelving> _Shelvings = new global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.Shelving>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnShelvingsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.Shelving> value);
        partial void OnShelvingsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LocationSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("LocationSingle")]
    public partial class LocationSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Location>
    {
        /// <summary>
        /// Initialize a new LocationSingle object.
        /// </summary>
        public LocationSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new LocationSingle object.
        /// </summary>
        public LocationSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new LocationSingle object.
        /// </summary>
        public LocationSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Location> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for LocationCollections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LocationCollections")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.LocationCollection> LocationCollections
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._LocationCollections == null))
                {
                    this._LocationCollections = Context.CreateQuery<global::HCLib.FlotationDevice.Service.Models.LocationCollection>(GetPath("LocationCollections"));
                }
                return this._LocationCollections;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.LocationCollection> _LocationCollections;
        /// <summary>
        /// There are no comments for Shelvings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Shelvings")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Shelving> Shelvings
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Shelvings == null))
                {
                    this._Shelvings = Context.CreateQuery<global::HCLib.FlotationDevice.Service.Models.Shelving>(GetPath("Shelvings"));
                }
                return this._Shelvings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Shelving> _Shelvings;
    }
    /// <summary>
    /// There are no comments for Location in the schema.
    /// </summary>
    /// <KeyProperties>
    /// LocationID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("LocationID")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Location")]
    public partial class Location : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Location object.
        /// </summary>
        /// <param name="locationID">Initial value of LocationID.</param>
        /// <param name="active">Initial value of Active.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static Location CreateLocation(int locationID, bool active)
        {
            Location location = new Location();
            location.LocationID = locationID;
            location.Active = active;
            return location;
        }
        /// <summary>
        /// There are no comments for Property LocationID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LocationID")]
        public int LocationID
        {
            get
            {
                return this._LocationID;
            }
            set
            {
                this.OnLocationIDChanging(value);
                this._LocationID = value;
                this.OnLocationIDChanged();
                this.OnPropertyChanged("LocationID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private int _LocationID;
        partial void OnLocationIDChanging(int value);
        partial void OnLocationIDChanged();
        /// <summary>
        /// There are no comments for Property LocationName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LocationName")]
        public string LocationName
        {
            get
            {
                return this._LocationName;
            }
            set
            {
                this.OnLocationNameChanging(value);
                this._LocationName = value;
                this.OnLocationNameChanged();
                this.OnPropertyChanged("LocationName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _LocationName;
        partial void OnLocationNameChanging(string value);
        partial void OnLocationNameChanged();
        /// <summary>
        /// There are no comments for Property LocationCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LocationCode")]
        public string LocationCode
        {
            get
            {
                return this._LocationCode;
            }
            set
            {
                this.OnLocationCodeChanging(value);
                this._LocationCode = value;
                this.OnLocationCodeChanged();
                this.OnPropertyChanged("LocationCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _LocationCode;
        partial void OnLocationCodeChanging(string value);
        partial void OnLocationCodeChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Active")]
        public bool Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this._Active = value;
                this.OnActiveChanged();
                this.OnPropertyChanged("Active");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private bool _Active;
        partial void OnActiveChanging(bool value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for Property LocationCollections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LocationCollections")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.LocationCollection> LocationCollections
        {
            get
            {
                return this._LocationCollections;
            }
            set
            {
                this.OnLocationCollectionsChanging(value);
                this._LocationCollections = value;
                this.OnLocationCollectionsChanged();
                this.OnPropertyChanged("LocationCollections");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.LocationCollection> _LocationCollections = new global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.LocationCollection>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnLocationCollectionsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.LocationCollection> value);
        partial void OnLocationCollectionsChanged();
        /// <summary>
        /// There are no comments for Property Shelvings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Shelvings")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.Shelving> Shelvings
        {
            get
            {
                return this._Shelvings;
            }
            set
            {
                this.OnShelvingsChanging(value);
                this._Shelvings = value;
                this.OnShelvingsChanged();
                this.OnPropertyChanged("Shelvings");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.Shelving> _Shelvings = new global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.Shelving>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnShelvingsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.Shelving> value);
        partial void OnShelvingsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ShelvingSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ShelvingSingle")]
    public partial class ShelvingSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Shelving>
    {
        /// <summary>
        /// Initialize a new ShelvingSingle object.
        /// </summary>
        public ShelvingSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ShelvingSingle object.
        /// </summary>
        public ShelvingSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ShelvingSingle object.
        /// </summary>
        public ShelvingSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Shelving> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for LocationCollection in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LocationCollection")]
        public global::HCLib.FlotationDevice.Service.Models.LocationCollectionSingle LocationCollection
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._LocationCollection == null))
                {
                    this._LocationCollection = new global::HCLib.FlotationDevice.Service.Models.LocationCollectionSingle(this.Context, GetPath("LocationCollection"));
                }
                return this._LocationCollection;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::HCLib.FlotationDevice.Service.Models.LocationCollectionSingle _LocationCollection;
        /// <summary>
        /// There are no comments for ShelfType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShelfType")]
        public global::HCLib.FlotationDevice.Service.Models.ShelfTypeSingle ShelfType
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ShelfType == null))
                {
                    this._ShelfType = new global::HCLib.FlotationDevice.Service.Models.ShelfTypeSingle(this.Context, GetPath("ShelfType"));
                }
                return this._ShelfType;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::HCLib.FlotationDevice.Service.Models.ShelfTypeSingle _ShelfType;
        /// <summary>
        /// There are no comments for Collection in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Collection")]
        public global::HCLib.FlotationDevice.Service.Models.CollectionSingle Collection
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Collection == null))
                {
                    this._Collection = new global::HCLib.FlotationDevice.Service.Models.CollectionSingle(this.Context, GetPath("Collection"));
                }
                return this._Collection;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::HCLib.FlotationDevice.Service.Models.CollectionSingle _Collection;
        /// <summary>
        /// There are no comments for Location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Location")]
        public global::HCLib.FlotationDevice.Service.Models.LocationSingle Location
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Location == null))
                {
                    this._Location = new global::HCLib.FlotationDevice.Service.Models.LocationSingle(this.Context, GetPath("Location"));
                }
                return this._Location;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::HCLib.FlotationDevice.Service.Models.LocationSingle _Location;
    }
    /// <summary>
    /// There are no comments for Shelving in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ShelvingID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ShelvingID")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Shelving")]
    public partial class Shelving : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Shelving object.
        /// </summary>
        /// <param name="shelvingID">Initial value of ShelvingID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static Shelving CreateShelving(int shelvingID)
        {
            Shelving shelving = new Shelving();
            shelving.ShelvingID = shelvingID;
            return shelving;
        }
        /// <summary>
        /// There are no comments for Property ShelvingID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShelvingID")]
        public int ShelvingID
        {
            get
            {
                return this._ShelvingID;
            }
            set
            {
                this.OnShelvingIDChanging(value);
                this._ShelvingID = value;
                this.OnShelvingIDChanged();
                this.OnPropertyChanged("ShelvingID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private int _ShelvingID;
        partial void OnShelvingIDChanging(int value);
        partial void OnShelvingIDChanged();
        /// <summary>
        /// There are no comments for Property LocationCollectionID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LocationCollectionID")]
        public global::System.Nullable<int> LocationCollectionID
        {
            get
            {
                return this._LocationCollectionID;
            }
            set
            {
                this.OnLocationCollectionIDChanging(value);
                this._LocationCollectionID = value;
                this.OnLocationCollectionIDChanged();
                this.OnPropertyChanged("LocationCollectionID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<int> _LocationCollectionID;
        partial void OnLocationCollectionIDChanging(global::System.Nullable<int> value);
        partial void OnLocationCollectionIDChanged();
        /// <summary>
        /// There are no comments for Property ShelfTypeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShelfTypeID")]
        public global::System.Nullable<int> ShelfTypeID
        {
            get
            {
                return this._ShelfTypeID;
            }
            set
            {
                this.OnShelfTypeIDChanging(value);
                this._ShelfTypeID = value;
                this.OnShelfTypeIDChanged();
                this.OnPropertyChanged("ShelfTypeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<int> _ShelfTypeID;
        partial void OnShelfTypeIDChanging(global::System.Nullable<int> value);
        partial void OnShelfTypeIDChanged();
        /// <summary>
        /// There are no comments for Property ShelfQty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShelfQty")]
        public global::System.Nullable<int> ShelfQty
        {
            get
            {
                return this._ShelfQty;
            }
            set
            {
                this.OnShelfQtyChanging(value);
                this._ShelfQty = value;
                this.OnShelfQtyChanged();
                this.OnPropertyChanged("ShelfQty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<int> _ShelfQty;
        partial void OnShelfQtyChanging(global::System.Nullable<int> value);
        partial void OnShelfQtyChanged();
        /// <summary>
        /// There are no comments for Property Length in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Length")]
        public global::System.Nullable<int> Length
        {
            get
            {
                return this._Length;
            }
            set
            {
                this.OnLengthChanging(value);
                this._Length = value;
                this.OnLengthChanged();
                this.OnPropertyChanged("Length");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<int> _Length;
        partial void OnLengthChanging(global::System.Nullable<int> value);
        partial void OnLengthChanged();
        /// <summary>
        /// There are no comments for Property RowQty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RowQty")]
        public global::System.Nullable<int> RowQty
        {
            get
            {
                return this._RowQty;
            }
            set
            {
                this.OnRowQtyChanging(value);
                this._RowQty = value;
                this.OnRowQtyChanged();
                this.OnPropertyChanged("RowQty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<int> _RowQty;
        partial void OnRowQtyChanging(global::System.Nullable<int> value);
        partial void OnRowQtyChanged();
        /// <summary>
        /// There are no comments for Property Note in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Note")]
        public string Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                this.OnNoteChanging(value);
                this._Note = value;
                this.OnNoteChanged();
                this.OnPropertyChanged("Note");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Note;
        partial void OnNoteChanging(string value);
        partial void OnNoteChanged();
        /// <summary>
        /// There are no comments for Property Updated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Updated")]
        public global::System.Nullable<global::System.DateTimeOffset> Updated
        {
            get
            {
                return this._Updated;
            }
            set
            {
                this.OnUpdatedChanging(value);
                this._Updated = value;
                this.OnUpdatedChanged();
                this.OnPropertyChanged("Updated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<global::System.DateTimeOffset> _Updated;
        partial void OnUpdatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnUpdatedChanged();
        /// <summary>
        /// There are no comments for Property CollectionID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CollectionID")]
        public global::System.Nullable<int> CollectionID
        {
            get
            {
                return this._CollectionID;
            }
            set
            {
                this.OnCollectionIDChanging(value);
                this._CollectionID = value;
                this.OnCollectionIDChanged();
                this.OnPropertyChanged("CollectionID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<int> _CollectionID;
        partial void OnCollectionIDChanging(global::System.Nullable<int> value);
        partial void OnCollectionIDChanged();
        /// <summary>
        /// There are no comments for Property LocationID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LocationID")]
        public global::System.Nullable<int> LocationID
        {
            get
            {
                return this._LocationID;
            }
            set
            {
                this.OnLocationIDChanging(value);
                this._LocationID = value;
                this.OnLocationIDChanged();
                this.OnPropertyChanged("LocationID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<int> _LocationID;
        partial void OnLocationIDChanging(global::System.Nullable<int> value);
        partial void OnLocationIDChanged();
        /// <summary>
        /// There are no comments for Property LocationCollection in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LocationCollection")]
        public global::HCLib.FlotationDevice.Service.Models.LocationCollection LocationCollection
        {
            get
            {
                return this._LocationCollection;
            }
            set
            {
                this.OnLocationCollectionChanging(value);
                this._LocationCollection = value;
                this.OnLocationCollectionChanged();
                this.OnPropertyChanged("LocationCollection");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::HCLib.FlotationDevice.Service.Models.LocationCollection _LocationCollection;
        partial void OnLocationCollectionChanging(global::HCLib.FlotationDevice.Service.Models.LocationCollection value);
        partial void OnLocationCollectionChanged();
        /// <summary>
        /// There are no comments for Property ShelfType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShelfType")]
        public global::HCLib.FlotationDevice.Service.Models.ShelfType ShelfType
        {
            get
            {
                return this._ShelfType;
            }
            set
            {
                this.OnShelfTypeChanging(value);
                this._ShelfType = value;
                this.OnShelfTypeChanged();
                this.OnPropertyChanged("ShelfType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::HCLib.FlotationDevice.Service.Models.ShelfType _ShelfType;
        partial void OnShelfTypeChanging(global::HCLib.FlotationDevice.Service.Models.ShelfType value);
        partial void OnShelfTypeChanged();
        /// <summary>
        /// There are no comments for Property Collection in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Collection")]
        public global::HCLib.FlotationDevice.Service.Models.Collection Collection
        {
            get
            {
                return this._Collection;
            }
            set
            {
                this.OnCollectionChanging(value);
                this._Collection = value;
                this.OnCollectionChanged();
                this.OnPropertyChanged("Collection");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::HCLib.FlotationDevice.Service.Models.Collection _Collection;
        partial void OnCollectionChanging(global::HCLib.FlotationDevice.Service.Models.Collection value);
        partial void OnCollectionChanged();
        /// <summary>
        /// There are no comments for Property Location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Location")]
        public global::HCLib.FlotationDevice.Service.Models.Location Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                this._Location = value;
                this.OnLocationChanged();
                this.OnPropertyChanged("Location");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::HCLib.FlotationDevice.Service.Models.Location _Location;
        partial void OnLocationChanging(global::HCLib.FlotationDevice.Service.Models.Location value);
        partial void OnLocationChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ShelfTypeSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ShelfTypeSingle")]
    public partial class ShelfTypeSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ShelfType>
    {
        /// <summary>
        /// Initialize a new ShelfTypeSingle object.
        /// </summary>
        public ShelfTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ShelfTypeSingle object.
        /// </summary>
        public ShelfTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ShelfTypeSingle object.
        /// </summary>
        public ShelfTypeSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ShelfType> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Shelvings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Shelvings")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Shelving> Shelvings
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Shelvings == null))
                {
                    this._Shelvings = Context.CreateQuery<global::HCLib.FlotationDevice.Service.Models.Shelving>(GetPath("Shelvings"));
                }
                return this._Shelvings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Shelving> _Shelvings;
    }
    /// <summary>
    /// There are no comments for ShelfType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ShelfTypeID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ShelfTypeID")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("ShelfType")]
    public partial class ShelfType : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ShelfType object.
        /// </summary>
        /// <param name="shelfTypeID">Initial value of ShelfTypeID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static ShelfType CreateShelfType(int shelfTypeID)
        {
            ShelfType shelfType = new ShelfType();
            shelfType.ShelfTypeID = shelfTypeID;
            return shelfType;
        }
        /// <summary>
        /// There are no comments for Property ShelfTypeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShelfTypeID")]
        public int ShelfTypeID
        {
            get
            {
                return this._ShelfTypeID;
            }
            set
            {
                this.OnShelfTypeIDChanging(value);
                this._ShelfTypeID = value;
                this.OnShelfTypeIDChanged();
                this.OnPropertyChanged("ShelfTypeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private int _ShelfTypeID;
        partial void OnShelfTypeIDChanging(int value);
        partial void OnShelfTypeIDChanged();
        /// <summary>
        /// There are no comments for Property ShelfType1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShelfType1")]
        public string ShelfType1
        {
            get
            {
                return this._ShelfType1;
            }
            set
            {
                this.OnShelfType1Changing(value);
                this._ShelfType1 = value;
                this.OnShelfType1Changed();
                this.OnPropertyChanged("ShelfType1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _ShelfType1;
        partial void OnShelfType1Changing(string value);
        partial void OnShelfType1Changed();
        /// <summary>
        /// There are no comments for Property Shelvings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Shelvings")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.Shelving> Shelvings
        {
            get
            {
                return this._Shelvings;
            }
            set
            {
                this.OnShelvingsChanging(value);
                this._Shelvings = value;
                this.OnShelvingsChanged();
                this.OnPropertyChanged("Shelvings");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.Shelving> _Shelvings = new global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.Shelving>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnShelvingsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::HCLib.FlotationDevice.Service.Models.Shelving> value);
        partial void OnShelvingsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::HCLib.FlotationDevice.Service.Models.LocationCollection as global::HCLib.FlotationDevice.Service.Models.LocationCollectionSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::HCLib.FlotationDevice.Service.Models.LocationCollectionSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.LocationCollection> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::HCLib.FlotationDevice.Service.Models.LocationCollectionSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::HCLib.FlotationDevice.Service.Models.LocationCollection as global::HCLib.FlotationDevice.Service.Models.LocationCollectionSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="locationCollectionID">The value of locationCollectionID</param>
        public static global::HCLib.FlotationDevice.Service.Models.LocationCollectionSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.LocationCollection> source,
            int locationCollectionID)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "LocationCollectionID", locationCollectionID }
            };
            return new global::HCLib.FlotationDevice.Service.Models.LocationCollectionSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::HCLib.FlotationDevice.Service.Models.Collection as global::HCLib.FlotationDevice.Service.Models.CollectionSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::HCLib.FlotationDevice.Service.Models.CollectionSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Collection> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::HCLib.FlotationDevice.Service.Models.CollectionSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::HCLib.FlotationDevice.Service.Models.Collection as global::HCLib.FlotationDevice.Service.Models.CollectionSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="collectionID">The value of collectionID</param>
        public static global::HCLib.FlotationDevice.Service.Models.CollectionSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Collection> source,
            int collectionID)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "CollectionID", collectionID }
            };
            return new global::HCLib.FlotationDevice.Service.Models.CollectionSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::HCLib.FlotationDevice.Service.Models.Location as global::HCLib.FlotationDevice.Service.Models.LocationSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::HCLib.FlotationDevice.Service.Models.LocationSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Location> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::HCLib.FlotationDevice.Service.Models.LocationSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::HCLib.FlotationDevice.Service.Models.Location as global::HCLib.FlotationDevice.Service.Models.LocationSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="locationID">The value of locationID</param>
        public static global::HCLib.FlotationDevice.Service.Models.LocationSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Location> source,
            int locationID)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "LocationID", locationID }
            };
            return new global::HCLib.FlotationDevice.Service.Models.LocationSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::HCLib.FlotationDevice.Service.Models.Shelving as global::HCLib.FlotationDevice.Service.Models.ShelvingSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::HCLib.FlotationDevice.Service.Models.ShelvingSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Shelving> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::HCLib.FlotationDevice.Service.Models.ShelvingSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::HCLib.FlotationDevice.Service.Models.Shelving as global::HCLib.FlotationDevice.Service.Models.ShelvingSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="shelvingID">The value of shelvingID</param>
        public static global::HCLib.FlotationDevice.Service.Models.ShelvingSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Shelving> source,
            int shelvingID)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ShelvingID", shelvingID }
            };
            return new global::HCLib.FlotationDevice.Service.Models.ShelvingSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::HCLib.FlotationDevice.Service.Models.ShelfType as global::HCLib.FlotationDevice.Service.Models.ShelfTypeSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::HCLib.FlotationDevice.Service.Models.ShelfTypeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.ShelfType> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::HCLib.FlotationDevice.Service.Models.ShelfTypeSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::HCLib.FlotationDevice.Service.Models.ShelfType as global::HCLib.FlotationDevice.Service.Models.ShelfTypeSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="shelfTypeID">The value of shelfTypeID</param>
        public static global::HCLib.FlotationDevice.Service.Models.ShelfTypeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.ShelfType> source,
            int shelfTypeID)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ShelfTypeID", shelfTypeID }
            };
            return new global::HCLib.FlotationDevice.Service.Models.ShelfTypeSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "HCLib.FlotationDevice.Service.Models", "HCLib.FlotationDevice.Service.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("HCLib.FlotationDevice.Service.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("HCLib.FlotationDevice.Service.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("HCLib.FlotationDevice.Service.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for LocationCollections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LocationCollections")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.LocationCollection> LocationCollections
        {
            get
            {
                if ((this._LocationCollections == null))
                {
                    this._LocationCollections = base.CreateQuery<global::HCLib.FlotationDevice.Service.Models.LocationCollection>("LocationCollections");
                }
                return this._LocationCollections;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.LocationCollection> _LocationCollections;
        /// <summary>
        /// There are no comments for Collections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Collections")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Collection> Collections
        {
            get
            {
                if ((this._Collections == null))
                {
                    this._Collections = base.CreateQuery<global::HCLib.FlotationDevice.Service.Models.Collection>("Collections");
                }
                return this._Collections;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Collection> _Collections;
        /// <summary>
        /// There are no comments for Locations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Locations")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Location> Locations
        {
            get
            {
                if ((this._Locations == null))
                {
                    this._Locations = base.CreateQuery<global::HCLib.FlotationDevice.Service.Models.Location>("Locations");
                }
                return this._Locations;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Location> _Locations;
        /// <summary>
        /// There are no comments for Shelvings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Shelvings")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Shelving> Shelvings
        {
            get
            {
                if ((this._Shelvings == null))
                {
                    this._Shelvings = base.CreateQuery<global::HCLib.FlotationDevice.Service.Models.Shelving>("Shelvings");
                }
                return this._Shelvings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.Shelving> _Shelvings;
        /// <summary>
        /// There are no comments for ShelfTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShelfTypes")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.ShelfType> ShelfTypes
        {
            get
            {
                if ((this._ShelfTypes == null))
                {
                    this._ShelfTypes = base.CreateQuery<global::HCLib.FlotationDevice.Service.Models.ShelfType>("ShelfTypes");
                }
                return this._ShelfTypes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::HCLib.FlotationDevice.Service.Models.ShelfType> _ShelfTypes;
        /// <summary>
        /// There are no comments for LocationCollections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public void AddToLocationCollections(global::HCLib.FlotationDevice.Service.Models.LocationCollection locationCollection)
        {
            base.AddObject("LocationCollections", locationCollection);
        }
        /// <summary>
        /// There are no comments for Collections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public void AddToCollections(global::HCLib.FlotationDevice.Service.Models.Collection collection)
        {
            base.AddObject("Collections", collection);
        }
        /// <summary>
        /// There are no comments for Locations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public void AddToLocations(global::HCLib.FlotationDevice.Service.Models.Location location)
        {
            base.AddObject("Locations", location);
        }
        /// <summary>
        /// There are no comments for Shelvings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public void AddToShelvings(global::HCLib.FlotationDevice.Service.Models.Shelving shelving)
        {
            base.AddObject("Shelvings", shelving);
        }
        /// <summary>
        /// There are no comments for ShelfTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public void AddToShelfTypes(global::HCLib.FlotationDevice.Service.Models.ShelfType shelfType)
        {
            base.AddObject("ShelfTypes", shelfType);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""HCLib.FlotationDevice.Service.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""LocationCollection"">
        <Key>
          <PropertyRef Name=""LocationCollectionID"" />
        </Key>
        <Property Name=""LocationCollectionID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""LocationID"" Type=""Edm.Int32"" />
        <Property Name=""CollectionID"" Type=""Edm.Int32"" />
        <Property Name=""CheckedInItems"" Type=""Edm.Int32"" />
        <NavigationProperty Name=""Collection"" Type=""HCLib.FlotationDevice.Service.Models.Collection"">
          <ReferentialConstraint Property=""CollectionID"" ReferencedProperty=""CollectionID"" />
        </NavigationProperty>
        <NavigationProperty Name=""Location"" Type=""HCLib.FlotationDevice.Service.Models.Location"">
          <ReferentialConstraint Property=""LocationID"" ReferencedProperty=""LocationID"" />
        </NavigationProperty>
        <NavigationProperty Name=""Shelvings"" Type=""Collection(HCLib.FlotationDevice.Service.Models.Shelving)"" />
      </EntityType>
      <EntityType Name=""Collection"">
        <Key>
          <PropertyRef Name=""CollectionID"" />
        </Key>
        <Property Name=""CollectionID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""CollectionName"" Type=""Edm.String"" />
        <Property Name=""CollectionCode"" Type=""Edm.String"" />
        <Property Name=""Active"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""AverageWidth"" Type=""Edm.Double"" />
        <NavigationProperty Name=""LocationCollections"" Type=""Collection(HCLib.FlotationDevice.Service.Models.LocationCollection)"" />
        <NavigationProperty Name=""Shelvings"" Type=""Collection(HCLib.FlotationDevice.Service.Models.Shelving)"" />
      </EntityType>
      <EntityType Name=""Location"">
        <Key>
          <PropertyRef Name=""LocationID"" />
        </Key>
        <Property Name=""LocationID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""LocationName"" Type=""Edm.String"" />
        <Property Name=""LocationCode"" Type=""Edm.String"" />
        <Property Name=""Active"" Type=""Edm.Boolean"" Nullable=""false"" />
        <NavigationProperty Name=""LocationCollections"" Type=""Collection(HCLib.FlotationDevice.Service.Models.LocationCollection)"" />
        <NavigationProperty Name=""Shelvings"" Type=""Collection(HCLib.FlotationDevice.Service.Models.Shelving)"" />
      </EntityType>
      <EntityType Name=""Shelving"">
        <Key>
          <PropertyRef Name=""ShelvingID"" />
        </Key>
        <Property Name=""ShelvingID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""LocationCollectionID"" Type=""Edm.Int32"" />
        <Property Name=""ShelfTypeID"" Type=""Edm.Int32"" />
        <Property Name=""ShelfQty"" Type=""Edm.Int32"" />
        <Property Name=""Length"" Type=""Edm.Int32"" />
        <Property Name=""RowQty"" Type=""Edm.Int32"" />
        <Property Name=""Note"" Type=""Edm.String"" />
        <Property Name=""Updated"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""CollectionID"" Type=""Edm.Int32"" />
        <Property Name=""LocationID"" Type=""Edm.Int32"" />
        <NavigationProperty Name=""LocationCollection"" Type=""HCLib.FlotationDevice.Service.Models.LocationCollection"">
          <ReferentialConstraint Property=""LocationCollectionID"" ReferencedProperty=""LocationCollectionID"" />
        </NavigationProperty>
        <NavigationProperty Name=""ShelfType"" Type=""HCLib.FlotationDevice.Service.Models.ShelfType"">
          <ReferentialConstraint Property=""ShelfTypeID"" ReferencedProperty=""ShelfTypeID"" />
        </NavigationProperty>
        <NavigationProperty Name=""Collection"" Type=""HCLib.FlotationDevice.Service.Models.Collection"">
          <ReferentialConstraint Property=""CollectionID"" ReferencedProperty=""CollectionID"" />
        </NavigationProperty>
        <NavigationProperty Name=""Location"" Type=""HCLib.FlotationDevice.Service.Models.Location"">
          <ReferentialConstraint Property=""LocationID"" ReferencedProperty=""LocationID"" />
        </NavigationProperty>
      </EntityType>
      <EntityType Name=""ShelfType"">
        <Key>
          <PropertyRef Name=""ShelfTypeID"" />
        </Key>
        <Property Name=""ShelfTypeID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""ShelfType1"" Type=""Edm.String"" />
        <NavigationProperty Name=""Shelvings"" Type=""Collection(HCLib.FlotationDevice.Service.Models.Shelving)"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""LocationCollections"" EntityType=""HCLib.FlotationDevice.Service.Models.LocationCollection"">
          <NavigationPropertyBinding Path=""Collection"" Target=""Collections"" />
          <NavigationPropertyBinding Path=""Location"" Target=""Locations"" />
          <NavigationPropertyBinding Path=""Shelvings"" Target=""Shelvings"" />
        </EntitySet>
        <EntitySet Name=""Collections"" EntityType=""HCLib.FlotationDevice.Service.Models.Collection"">
          <NavigationPropertyBinding Path=""LocationCollections"" Target=""LocationCollections"" />
          <NavigationPropertyBinding Path=""Shelvings"" Target=""Shelvings"" />
        </EntitySet>
        <EntitySet Name=""Locations"" EntityType=""HCLib.FlotationDevice.Service.Models.Location"">
          <NavigationPropertyBinding Path=""LocationCollections"" Target=""LocationCollections"" />
          <NavigationPropertyBinding Path=""Shelvings"" Target=""Shelvings"" />
        </EntitySet>
        <EntitySet Name=""Shelvings"" EntityType=""HCLib.FlotationDevice.Service.Models.Shelving"">
          <NavigationPropertyBinding Path=""Collection"" Target=""Collections"" />
          <NavigationPropertyBinding Path=""Location"" Target=""Locations"" />
          <NavigationPropertyBinding Path=""LocationCollection"" Target=""LocationCollections"" />
          <NavigationPropertyBinding Path=""ShelfType"" Target=""ShelfTypes"" />
        </EntitySet>
        <EntitySet Name=""ShelfTypes"" EntityType=""HCLib.FlotationDevice.Service.Models.ShelfType"">
          <NavigationPropertyBinding Path=""Shelvings"" Target=""Shelvings"" />
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;
                    
                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
                        global::System.Text.StringBuilder errorMessages = new System.Text.StringBuilder();
                        foreach (var error in errors)
                        {
                            errorMessages.Append(error.ErrorMessage);
                            errorMessages.Append("; ");
                        }
                        throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
